equity: 10000000
risk: 0.01
max_positions: 5
universe_csv: "kospi200.csv"
positions_csv: "positions.csv"
lookback: 120

entry:
  watchlist:
  near_hhv30_pct: 0.01   # HHV30의 1% 이내이면 근접 후보
  hhv_window: 30
  buffer: 0.001
  require_ma_trend: true

exit:
  stop_atr_multiple: 1.5
  ma_exit: true

telegram:
  enabled: true
  token_env: "TELEGRAM_BOT_TOKEN"
  chat_id_env: "TELEGRAM_CHAT_ID"

ntfy:
  enabled: false
  url_env: "NTFY_URL"

market_hours:
  start_kst: "09:00"
  end_kst: "15:30"



