equity: 10000000
risk: 0.01
max_positions: 5

# ▶ 로컬 데이터 디렉토리 추가
data_dir: "C:\\KiwoomBot32\\data"

# ▶ 유니버스 경로/포맷 맞추기: code[,name]
universe_csv: "universe\\kospi200_codes.csv"

# 포지션 파일 (code,name,entry_date,entry_price,shares)
positions_csv: "positions.csv"

lookback: 120

entry:
  watchlist:
  near_hhv30_pct: 0.01
  hhv_window: 30
  buffer: 0.001
  require_ma_trend: true

exit:
  stop_atr_multiple: 1.5
  ma_exit: true
  # ▶ 키 이름 유지: 스캐너에서 time_stop_days로 읽히게 패치할 것
  time_stop: 5

filters:
  rs_window: 120
  rs_min: 1.1
  volume_factor: 1.5

telegram:
  enabled: true
  token_env: "TELEGRAM_BOT_TOKEN"
  chat_id_env: "TELEGRAM_CHAT_ID"

ntfy:
  enabled: false
  url_env: "NTFY_URL"

market_hours:
  start_kst: "09:00"
  end_kst: "15:30"

notifications:
  summary_every_min: 60










