equity: 10000000
risk: 0.01
max_positions: 5
universe_csv: "kospi200.csv"
positions_csv: "positions.csv"
lookback: 120

entry:
  watchlist:
  near_hhv30_pct: 0.01   # HHV30의 1% 이내이면 근접 후보
  hhv_window: 30
  buffer: 0.001
  require_ma_trend: true

exit:
  stop_atr_multiple: 1.5
  ma_exit: true
  time_stop: 5

filters:
  rs_window: 120        # RS 계산 기간(일): 60 또는 120 추천
  rs_min: 1.1          # RS 하한: 1.0=시장 이상, 1.05=시장 대비 +5% 우위
  volume_factor: 1.5


telegram:
  enabled: true
  token_env: "TELEGRAM_BOT_TOKEN"
  chat_id_env: "TELEGRAM_CHAT_ID"

ntfy:
  enabled: false
  url_env: "NTFY_URL"

market_hours:
  start_kst: "09:00"
  end_kst: "15:30"

notifications:
  summary_every_min: 60   # 60=매시 정각에만 요약 발송 (5, 10, 30 등도 가능)
  








